INSERT INTO `certificate`(`email`, `name`) VALUES 
('pajenagosalvadora@gmail.com','Abbie S. Pajenago'),
('adrianranido9@gmail.com','Adrian Dirk S. Ranido'),
('adrian.michael.e.del.rosario@gmail.com','Adrian Michael E. Del Rosario'),
('ailajanellamarino10@gmail.com','Aila Janella D. M. Mariño'),
('alaissa.laoang@neu.edu.ph','Alaissa V. Laoang'),
('aljayducusin4@gmail.com','Aljay A. Ducusin'),
('allevanz.mallanao@neu.edu.ph','Allevanz B. Mallanao'),
('al.abrigana@gmail.com','Alyssa A. Abrigana'),
('dayaoalyssaneri@gmail.com','Alyssa Neri I. Dayao'),
('ms.andreamedina@gmail.com','Andrea Nicole E. Medina'),
('chamberlainzuniga@gmail.com','Andrew Chamberlain A. Zuñiga VII'),
('vanjaneth17@gmail.com','Anjaneth A. Villegas'),
('annamarietaduran@gmail.com','Anna Marie C. Taduran'),
('ariellejanbendicio@gmail.com','Arielle Jan J. Bendicio'),
('arnolddelacruz018@gmail.com','Arnold C. Dela Cruz Jr.'),
('nc.aronmar.organo@cvsu.edu.ph','Aron Mar D. Organo'),
('arwinnemuelcalzada@gmail.com','Arwin Nemuel B. Calzada'),
('javier.brnlyn123@gmail.com','Bernalyn L. Valdez'),
('yabi.cantor@gmail.com','Biyaya P. Cantor'),
('cprualizo.ccit@unp.edu.ph','Cain P. Rualizo'),
('agbuyacamille17@gmail.com','Camille C. Agbuya'),
('tacaisancamillekisha@gmail.com','Camille Kisha A Tacaisan'),
('carencegalecanlapan@gmail.com','Canlapan, Carence Gale S.'), 
('carmela.alvior@perpetualdalta.edu.ph','Carmela M. Alvior'),
('catherinejutba6@gmail.com','Catherine E. Jutba'),
('cath.ablog05@gmail.com','Catherine G. Ablog'),
('celesdelacruz17@gmail.com','Celes M. Dela Cruz'),
('charltonjeffkanoy@gmail.com','Charlton Jeff Kanoy'),
('christamante47@gmail.com','Christian Jay P. Amante'),
('christianpnicolas@gmail.com','Christian P. Nicolas'),
('christina.fontanilla@neu.edu.ph','Christina Fontanilla'),
('christine.joyce.cajayon.aton@gmail.com','Christine Joyce C. Aton'),
('chriziamaebenosa7@gmail.com','Chrizia Mae A. Benosa'),
('chrystallineg@gmail.com','Chrystalline S. Gopio'),
('ciarajoybondoc10@gmail.com','Ciara Joy C. Bondoc'),
('clarissa.palabay@neu.edu.ph','Clarissa Mae M. Palabay'),
('magdadaro.clyde.08242002@gmail.com','Clyde S. Magdadaro'),
('czareeborromeoligero@gmail.com','Czaree B. Ligero'),
('buenaventedaniellakyle@gmail.com','Daniella Kyle Buenavente'),
('torrentejayar01@gmail.com','Danilo Torrente Jr.'),
('david.laurence.magbanua@gmail.com','David Laurence C. Magbanua'),
('alvarez.diana.04222003@gmail.com','Diana P. Alvarez'),
('diane.fabian@neu.edu.ph','Diane I. Fabian'),
('dimemoretuzon02@gmail.com','Dimemore P. Tuzon'),
('draizenjohn@gmail.com','Draizen John R. Bernal'),
('ej.rirao1436@gmail.com','Edward John L. Rirao'),
('sehunnie289@gmail.com','Eloisa-Ann M. Madera'),
('ashcabanit@gmail.com','Elyssa Ashley D. Cabanit'),
('emmanuelbajan0@gmail.com','Emmanuel C. Bajan'),
('ethanjexatienza@gmail.com','Ethan Jex T. Atienza'),
('thelcapayas@gmail.com','Ethel S. Capayas'),
('ezradevilla8@gmail.com','Ezra P. De Villa'),
('gabrieltadeocruz@gmail.com','Gabriel T. Cruz'),
('catabas.gabrielle.ann@gmail.com','Gabrielle Ann D. Catabas'),
('geehon.gamiao@neu.edu.ph','Geehon Lorein S. Gamiao'),
('onartsop22@gmail.com','Gemima Glory A. Postrano'),
('geraldmantequilla@gmail.com','Gerald G. Mantequilla'),
('gerry.garcia@my.jru.edu','Gerry O. Garcia'),
('glazlesandoval0911@gmail.com','Glazle D. Sandoval'),
('gfjcabrera@neu.edu.ph','Glori Faye Junine J. Cabrera'),
('gracielarcillacornelio28@gmail.com','Graciel A. Cornelio'),
('ianalexandervillanueva21@gmail.com','Ian Alexander C. Villanueva'),
('ilonahdanhizon@gmail.com','Ilonah Dan S. Hizon'),
('israhmariel09@gmail.com','Israh Mariel S. Quintana'),
('alvarinaivan11@gmail.com','Ivan T. Alvarina'),
('jailaniplasencia.jp15@gmail.com','Jailani G. Plasencia'),
('jandale.agcaoili@neu.edu.ph','Jandale Justine T. Agcaoili'),
('marojasmin1@gmail.com','Jasmin Maro'),
('jay.manuel@neu.edu.ph','Jay Mark T. Manuel'),
('jrm356465@gmail.com','Jean Rose M. Lacaben'),
('jeanne.laquio.flores@gmail.com','Jeanne L. Flores'),
('jelly.anne.talacay.raba@gmail.com','Jelly Anne T. Raba'),
('lorjennifer373@gmail.com','Jennifer B. Lor'),
('jennymae.yap027@gmail.com','Jenny Mae R. Yap'),
('noynayjennyrose@gmail.com','Jenny Rose A. Noynay'),
('awacayjerryfrias@gmail.com','Jerry F. Awacay Jr.'),
('jerwin.nico.vicente.hugo@gmail.com','Jerwin Nico V. Hugo'),
('jessamae.felicitas.cariaga@gmail.com','Jessa Mae F. Cariaga'),
('jethroarielyuanfuentesumlas@gmail.com','Jethro Ariel Yuan F. Umlas'),
('jevan.serrano@neu.edu.ph','Jevan A. Serrano'),
('jhoncel.labrador.villar@gmail.com','Jhoncel L. Villar'),
('201911036@gordoncollege.edu.ph','Jiean Marc P. Estudillo'),
('tapangcojoana30@gmail.com','Joana Marie T. San Jose'),
('papellerojobet@gmail.com','Jobet Adrian E Papellero'),
('jocomagdaraog@gmail.com','Joco A. Magdaraog'),
('silmarojc@gmail.com','John Carlo D. Silmaro'),
('johncarlo.mandia22@gmail.com','John Carlo Mandia'),
('johncaloylacsa@gmail.com','John Carlos Lacsa'),
('sarciajohnkimcarlo@gmail.com','John Kim Carlo C. Sarcia'),
('diacamosjohnmark@gmail.com','John Mark C. Diacamos'),
('gepulla.johnmichael.01182003@gmail.com','John Michael Y. Gepulla'),
('jpramos0700@gmail.com','John Paul A. Ramos'),
('john.philip.rivera.cudas@gmail.com','John Philip R. Cudas'),
('john.rey.taniega.consulta@gmail.com','John Rey T. Consulta'),
('jonahfefadirugao@gmail.com','Jonah Fe Fadirugao'),
('jonalyn.tibigar.frias@gmail.com','Jonalyn T. Frias'),
('leonidajonathan14@gmail.com','Jonathan R. Leonida'),
('viseyjonley22@gmail.com','Jonley Roman Andrei C. Visey'),
('josephaldea26@gmail.com','Joseph T. Aldea'),
('joshua.lising@neu.edu.ph','Joshua J. Lising'),
('bacanijoshua01@gmail.com','Joshua M. Bacani'),
('norioste.joshua.1@gmail.com','Joshua M. Norioste'),
('annedelossantosbantilan@gmail.com','Jovani Anne S. Bantilan'),
('juliemaybelen@gmail.com','Julie May J. Belen'),
('paano14325@gmail.com','Julius Angelo A. Paano'),
('nacariojullianekeith@gmail.com','Julliane Keith Nacario'),
('jurymarsnicolas@gmail.com','Jury Mars A. Nicolas'),
('karen.mae.travisonda.carillo@gmail.com','Karen Mae T. Carillo'),
('karlperlas810@gmail.com','Karl Angelo M. Perlas'),
('katrinaenrile2@gmail.com','katrina O. Enrile'),
('katrinaplandes1@gmail.com','Katrina V. Plandes'),
('qkdpdomogma@tip.edu.ph','Kenneth David P. Domogma'),
('khyla.cadag@neu.edu.ph','Khyla Mafee Y. Cadag'),
('kiara.raye.carganillo@gmail.com','Kiara Raye P. Carganillo'),
('tkimrussel@gmail.com','Kim Russel Sotomil Tugbo'),
('kizzyangelavea032405@gmail.com','Kizzy Angela B. Vea'),
('kristamaeemonares@gmail.com','Krista Mae Monares'),
('kristal.bolano.dordas@gmail.com','Kristal B. Dordas'),
('kristianicoleramirez@gmail.com','Kristia Nicole P. Ramirez'),
('krystalmanamtam.mlis2019@gmail.com','Krystal L. Manamtam'),
('pabalan26@gmail.com','Kurt Jovince P. Pabalan'),
('kylamarielgabuay@gmail.com','Kyla Mariel Q. Gabuay'),
('lady.vilar@neu.edu.ph','Lady Mae M. Vilar'),
('lancedanielgallos4@gmail.com','Lance Daniel G. Gallos'),
('larine.lopez@neu.edu.ph','Larine L. Lopez'),
('lei.bitanga@neu.edu.ph','Lei Darlin R. Bitanga'),
('love.tagum@neu.edu.ph','Love L. Tagum'),
('luisapales16@gmail.com','Luisa O. Palis'),
('lycha.aragon@neu.edu.ph','Lycha L. Aragon'),
('lykamaemarzano09@gmail.com','Lyka Mae B. Marzano'),
('ma.christina.hementera@neu.edu.ph','Ma. Christina S. Hementera'),
('mae.gines@neu.edu.ph','Mae B. Gines'),
('villanuevamariafe92@gmail.com','Mariafe R. Villanueva'),
('itssmeyel@gmail.com','Mariel A. Guico'),
('mariel005hernandez@gmail.com','Mariel B. Hernandez'),
('markalvior92@gmail.com','Mark A. Alvior'),
('devillamarkchristian0440@gmail.com','Mark Christian A. De Villa'),
('neilgardon@gmail.com','Mark Neil A. Gardon'),
('marktrapela60@gmail.com','Mark Steven B. Trapela'),
('marlon.union.eballes@gmail.com','Marlon U. Eballes'),
('marudustinlloyd@gmail.com','Maru, Dustin Lloyd R.'),
('mryjnmenor11@gmail.com','Mary Jane S. Menor'),
('maryjoedel.congreso@gmail.com','Mary Joedel Congreso'),
('marygabriel014@gmail.com','Mary P. Gabriel'),
('maximus.alvarado26@gmail.com','Maximus V. Alvarado'),
('merinellastotomas06@gmail.com','Merinella A. Sto. Tomas'),
('gayetanomhelvilyn@gmail.com','Mhelvilyn S. Gayetano'),
('micoolondriz1984@gmail.com','Michael Angelo M. Olondriz'),
('milka.deleon@neu.edu.ph','Milka B. De Leon'),
('fajardomilky884@gmail.com','Milky D. Fajardo'),
('asulajhymalr@gmai.com','Mohammad Nur-Jhymalr M. Asula'),
('moniqueosal8@gmail.com','Monique G. Osal'),
('xnathanielalbanez@gmail.com','Nathaniel R. Albañez'),
('anenheruela@gmail.com','Nena N. Heruela'),
('nickareyes10@gmail.com','Nicka Ella G. Reyes'),
('nicolearetano417@gmail.com','Nicole Aretaño'),
('nicole.salazar@neu.edu.ph','Nicole Ingrid Salazar'),
('nina.charlize.aparicio.francisco@gmail.com','Nina Charlize A. Francisco'),
('pascualeon0415@gmail.com','Noel S. Pascua'),
('vinoya.noriel@gmail.com','Noriel C. Vinoya'),
('njocampo77@gmail.com','Nory Mojacko S. Ocampo'),
('ngpantalan@gmail.com','Nur Gina T. Pantalan'),
('roquepatriciaann@gmail.com','Patricia Ann R. Arends'),
('salgadopatrick37@gmail.com','Patrick F. Salgado'),
('princessdsgana20@gmail.com','Princess Dennielle S. Gaña'),
('cessafranco@gmail.com','Princess Dydred V. Franco'),
('princess.maluyo@neu.edu.ph','Princess Lea Mae P. Maluyo'),
('quindudero@gmail.com','Quin D. Dudero'),
('scorcherthug@gmail.com','Ralph Andrei A. Encarnacion'),
('ralphmichaelreyes@gmail.com','Ralph Michael C. Reyes'),
('raynard.castro@neu.edu.ph','Raynard Andrie O. Castro'),
('razelle.balmes.domingo@gmail.com','Razelle B. Domingo'),
('regine.lorete.23@gmail.com','Regine C. Lorete'),
('renzo.tanguin2@gmail.com','Renzo James C. Tanguin'),
('reymangobrin00@gmail.com','Reyman M. Gobrin'),
('picsreyna1@gmail.com','Reyna D. Pica'),
('leiza.ricca@gmail.com','Ricca Leiza C. Dela Cruz'),
('riza.jimenez@neu.edu.ph','Riza V. Jimenez'),
('rizzamaalihan@gmail.com','Rizzabeth Joy A. Maalihan'),
('rucemelldexbruce1@gmail.com','Rucemell Dex D. Bruce'),
('raberulfhlorenz@gmail.com','Rulfh Lorenz R. Rabe'),
('ryan.aninang.hulleza@gmail.com','Ryan A. Hulleza'),
('ryan.miguel.valencia.deleon@gmail.com','Ryan Miguel V. De Leon'),
('seanyadao0330@gmail.com','Sean Y. Yadao'),
('srefuerzo@student.dmmmsu.edu.ph','Sherby Ann O. Refuerzo'),
('sophiaelaine0605@gmail.com','Sophia Elaine M. Agua'),
('slvmprr@gmail.com','Sylvia May P. Parra'),
('terence.jhune.gutib.chavez@gmail.com','Terence Jhune G. Chavez'),
('vanessa.alfaro@neu.edu.ph','Vanessa A. Alfaro'),
('vince.paragoso.ricaforte@gmail.com','Vince P. Ricaforte'),
('kentwrufila@gmail.com','Warnest Kent V. Rufila'),
('ynarose.samin137@gmail.com','Yna Rose P. Samin'),
('zanderveneracion06@gmail.com','Zander Ven R. Bustamante');
