INSERT INTO `certificate`(`email`, `name`) VALUES 
('aira.estalilla.alvarez@gmail.com','Alvarez, Aira Estalilla'),
('angilica.asia@gmail.com','Asia, Angilica B.'),
('gabriel.boctoy.jr@gmail.com','Boctoy, Gabriel Jr. Brome'),
('jhonel.dimamay.camarillo@gmail.com','Camarillo,Jhonel Dimamay'),
('carl.vincent.paciente.chua@gmail.com','Chua, Carl Vincent Paciente'),
('blekxsy.jean.ancheta.daloso@gmail.com','Daloso, Blekxsy Jean Ancheta'),
('aldrin.deasas.estanislao@gmail.com','Estanislao, Aldrin D.A.'),
('luis.branden.petargue.garo@gmail.com','Garo, Luis Branden, Petargue'),
('jovito.isorena.jr@gmail.com','Isorena, Jovito Jr., Briones'),
('james.matthew.jimenez@gmail.com','Jimenez, James Matthew De Leon'),
('anna.aquino.manansala@gmail.com','Manansala, Anna Aquino'),
('bianca.lou.mendoza08152000@gmail.com','Mendoza, Bianca Lou Cabaluna'),
('lougen.desaliza.morales@gmail.com','Morales, Lougen Desaliza.'),
('vincent.charles.nobo@gmail.com','Nobo, Vincent Charles Olalo'),
('edmary.pambid@gmail.com','Pambid, Edmary Meiji R.'),
('rochelle.dacoco.songalia@gmail.com','Rochelle Songalia'),
('elven.a.sajorda@gmail.com','Sajorda, Elven A.'),
('leomar.tariao.sanguenza@gmail.com','Sanguenza Leomar T.'),
('john.patrick.naluz.solis@gmail.com','Solis, John Patrick Naluz'),
('jhon.carlos.cortez.tamba@gmail.com','Tamba, Jhon Carlos Cortez'),
('jethroarielyuanfuentesumlas@gmail.com','Umlas, Jethro Ariel Yuan Fuentes'),
('norlito.sillano.untalasco@gmail.com','Untalasco, Norlito, Sillano');
